server:
  port: 9000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: compte-id
          uri: lb://comptes
          predicates:
            - Path=/comptes/**
        - id: carte-id
          uri: lb://cartes
          predicates:
            - Path=/cartes/**